[package]
name = "ignore"
description = "Gitignore generator"
version = "0.1.0"
edition = "2021"
keywords = ["git", "ignore", "generator", "cli"]
readme = "README.md"
license = "MIT"

[dependencies]
clap = { version = "3.2.8", features = ["cargo"] }
triple_accel = "*"
walkdir = "2.3.2"
dirs = "1.0.4"
colored = "2"